repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        files: ^backend/.*$
      - id: ruff-format
        files: ^backend/.*$

  # TODO: Refactor to only run in /backend directory
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv --project backend run mypy backend
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv --project backend run pytest backend
        language: system
        pass_filenames: false